### ISSUE TITLE
crear password para usuario root

### ISSUE THREAD

**Issue by goodengineer** [logo-writer/queveo#2]
El usuario root deberia tener password siempre. Para cambiar la password primero tenes que:
* conectarte a mysql escribiendo `mysql` en consola
* asegurarte que estas usando la base de datos de mysql escribiendo `use mysql`

una vez que hiciste los 2 primeros pasos, ahora tenes que correr el statement SQL que cambia la password al usuario root. es asi:
```sql
# esto es un comment
# remplaza new_password con la password que quieras ponerle al usuario root
SET PASSWORD FOR 'root'@'localhost' = 'new_password';
```

fuente: https://www.geeksforgeeks.org/mysql-change-user-password/

acordate que despues de cambiar la password, para volver a conectarte a mysql como usuario root tenes que correr `mysql -u root -p` y te va a pedir la password que hayas configurado

trello: https://trello.com/c/LJBDWrR8/2-crear-password-para-usuario-root

**Comment by logo-writer** [comment]
Buen día locoo! Cuando escribo **mysql** en la consola me tira el siguiente error:

![imagen](https://user-images.githubusercontent.com/29823485/49381885-b9d48a80-f6f3-11e8-8073-45d99defb960.png)

**Comment by logo-writer** [comment]
Grande loco! ya está está resuelto. Tiene nuevamente el pass anterior funcionando. Ahora pongo la tarjeta de Trello en **DONE**

![imagen](https://user-images.githubusercontent.com/29823485/49382275-cdccbc00-f6f4-11e8-8bc7-27e4fb8ab34c.png)

**Comment by goodengineer** [comment]
@logo-writer excelente! ademas de poner el ticket en `DONE` podes darle Close al issue tambien, tenes un boton abajo para eso

**Comment by logo-writer** [comment]
Genial!
